### ISSUE TITLE
Unable to save email to regsitration list

### ISSUE THREAD

**Issue by n0byk** [coqui-ai/STT-models#10]
Can't put email and can't download models.

Please enter your email for model download - didnt work

**Comment by kdavis-coqui** [comment]
Could you describe your problem in more detail?

From [our model download page](https://coqui.ai/models) I'm able to

- Select a model's page, e.g. [German STT v0.0.1 (Jaco-Assistant)](https://coqui.ai/german/jaco-assistant/v0.0.1) 
- Click on "Enter Email to Download"
- Enter my email
- Click on a model, e.g. model.tflite
- Download the linked model

without any problems

**Comment by n0byk** [comment]
same steps but models is https://coqui.ai/russian/jemeyer/v0.1.0

**Comment by n0byk** [comment]
now its working tnx

**Comment by reuben** [comment]
A similar intermittent problem was reported on Gitter a few days ago. Could we have a problem with the lambda function or with the backend behind it that we need to double check?
