### ISSUE TITLE
yesno model: training data not available

### ISSUE THREAD

**Issue by jeremiahrose** [coqui-ai/STT-models#6]
The documentation ([here](https://coqui.ai/english/coqui/yesno-v0.0.1)) for the English yesno model says that the model was trained on the Common Voice Target Segments Corpus.

However this corpus does not seem to be available online. The documentation should provide a link to the location of this dataset.

**Comment by reuben** [comment]
https://commonvoice.mozilla.org/en/datasets

**Comment by reuben** [comment]
And I guess generally the full metadata is available on this repo: https://github.com/common-voice/cv-dataset/

**Comment by jeremiahrose** [comment]
Ah, great. The Single Word Target download is really not obvious on that page. Thankyou
